config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'events#index'
  resources :events
  get 'events/:id/users', to: 'events#users', as: :users
  put 'events/:id/update_users', to: 'events#update_users', as: :update_users
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users

  validates_presence_of :name, :date

  scope :past, -> { where('date < ?', Date.today) }
  scope :feature, -> { where('date > ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :users, :update_users]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
    gon.all_events = @events
    gon.visited_events = @events.where(visited_flag: true)
    gon.not_visited_events = @events.where(visited_flag: false)
    gon.past_events = @events.past
    gon.feature_events = @events.feature
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.users << current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def users
    @users = @event.users
    @all_users_except_current = User.where.not(id: current_user.id)
  end

  def update_users
    user_ids = params[:users].present? ? params[:users] : []
    user_ids << current_user.id
    respond_to do |format|
      if @event.update_attributes(user_ids: user_ids)
        format.html { redirect_to users_path(@event), notice: 'Users were successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :index }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :visited_flag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :date %>
    <%= f.input :visited_flag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Event', new_event_path, class: 'btn btn-success pull-right' %>

<h1>Events</h1>

<div class="filters">
  <a class="btn btn-primary" id="all-events">All events</a>
  <a class="btn btn-primary" id="visited-events">Visited events</a>
  <a class="btn btn-primary" id="not-visited-events">Not visited events</a>
  <a class="btn btn-primary" id="past-events">Past events</a>
  <a class="btn btn-primary" id="feature-events">Feature events</a>
</div>

<table id="events" data-toggle="table"></table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-group">
  <label>Name: </label>
  <label><%= @event.name %></label>
</div>
<div class="form-group">
  <label>Date: </label>
  <label><%= @event.date %></label>
</div>
<div class="form-group">
  <label>Visited:</label>
  <label><%= @event.visited_flag ? 'Yes' : 'No' %></label>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/users.html.erb
<h1>Users</h1>

<%= form_tag update_users_path(@event), method: :put, :class => 'form-search' do %>
    <%= select_tag 'users[]', options_from_collection_for_select(@all_users_except_current, :id, :email, @users.ids),
                   multiple: true, size: '10%', class: 'form-control' %>

    <%= submit_tag 'Add users', class: 'btn btn-success add-users-btn' %>
<% end %>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>
  </head>

  <body>
    <%= include_gon %>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="navbar-collapse collpase">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Home', root_path %></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <% if current_user %>
                  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                  <li><a><%= current_user.email %></a></li>
              <% else %>
                  <li><%= link_to 'Sign In', new_user_session_path %></li>
                  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>